keys:
  ## Users
  - &florian-yubikey CFAA36038DF83F58F38090E2358EE66F828961B3
  - &florian_other_yubikey 6CC9DAFA22A1DB345F18A7AD5437D56471EC435B
  - &sotiris-primary-yubikey 7FBACEF23172884FF4967ABCF9E644AF94BE1EAE
  - &sotiris-backup-yubikey  98FD09AC654B27772A03E6C7C0DC5C74462B385B
  - &sotiris-c-yubikey       93E75346EC76A38F684EFA248125744461D04398
  ## Hosts
  - &nix-asta2012-dc d0e5fcf0861474ca0da4b5cc5538a1ba2f123b83
  - &nix-asta2012-dc-01 5e597c24169388784ef183a09d72b03aceee3c54
  - &nix-authentik 28528b7b6322273d9c4178da8c125eb8d6231af2
  - &nix-nextcloud 6929705d3549cc8d112ad656ec4fabf6aaefe763
  - &nix-wordpress ae6f1f5c96be2434407369059eb3799f71bc7edf
  - &nix-wireguard 3eb256e34ecdccf45aa7b4982bb217347ac00885
  - &it-laptop bc4411e216f4f87c945dd8f7c7df1be1dcba335e
  - &nix-webserver e488a8340ef5a7b34ad32aa120c51cdbd64d4ac0
  - &nix-samba-dc 2867d27b003006b1f3aaae218a41fb0bf5033e81
  - &nix-samba-dc-01 df414f5dc0babbe639ab91b3bbfa14b808b56972
  - &nix-samba-fs b6e78f63523f66cd29a3f9e4ec7f479f02e439e4
  - &nix-build e1001e8f97a70d863c766ad334b1d990ee9a3226
  - &nix-postgres 1d4a5ee9d9497dc76130cd0f5d57fefee09727bf
creation_rules:
  - path_regex: secrets/nix-postgresql*
    key_groups:
      - pgp:
        - *florian-yubikey
        - *florian_other_yubikey
        - *nix-postgres
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
  - path_regex: secrets/nix-samba-fs*
    key_groups:
      - pgp:
        - *florian-yubikey
        - *florian_other_yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
        - *nix-samba-fs
  - path_regex: secrets/nix-asta2012-dc*
    key_groups:
      - pgp:
        - *florian-yubikey
        - *florian_other_yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
        - *nix-asta2012-dc
        - *nix-asta2012-dc-01
  - path_regex: secrets/nix-samba-dc*
    key_groups:
      - pgp:
        - *florian-yubikey
        - *florian_other_yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
        - *nix-samba-dc
        - *nix-samba-dc-01
  - path_regex: secrets/nix-wireguard.yaml
    key_groups:
      - pgp:
        - *nix-wireguard
        - *florian-yubikey
        - *florian_other_yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
  - path_regex: secrets/nix-webserver*
    key_groups:
      - pgp:
        - *florian_other_yubikey
        - *florian-yubikey
        - *nix-webserver
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
  - path_regex: secrets/nix-nextcloud*
    key_groups:
      - pgp:
        - *nix-nextcloud
        - *florian_other_yubikey
        - *florian-yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey
  - path_regex: secrets/nix-build
    key_groups:
      - pgp:
        - *nix-build
        - *florian_other_yubikey
        - *florian-yubikey
        - *sotiris-primary-yubikey
        - *sotiris-backup-yubikey
        - *sotiris-c-yubikey

