keys:
  ## Users
  - &other_yubikey 6CC9DAFA22A1DB345F18A7AD5437D56471EC435B
  ## Hosts
  - &nix-nextcloud FE8BEEC49A55525A7ACD7E891A26C149D992F306
  - &nix-wordpress ae6f1f5c96be2434407369059eb3799f71bc7edf
creation_rules:
  - path_regex: secrets/nix-nextcloud.yaml
    key_groups:
      - pgp:
        - *nix-nextcloud
        - *other_yubikey
  - path_regex: secrets/nix-wordpress.yaml
    key_groups:
      - pgp:
        - *nix-wordpress
        - *other_yubikey
