# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];
  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["dm-snapshot"];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [
      "subvol=root"
    ];
  };

  boot.initrd.systemd.services.cleanRoot = {
    description = "Clean Root Directory and Backup current Root";
    wantedBy = [
      "initrd.target"
    ];
    after = [
      #LUKS Decryption
      "systemd-cryptsetup@cryptroot.service"
    ];
    before = [
      "sysroot.mount"
    ];
    unitConfig.DefaultDependencies = "no";
    serviceConfig.Type = "oneshot";
    script = ''
      # Scan for new LVM file systems
      vgscan
      vgchange -ay

      # Backup previous root
      mkdir /btrfs_tmp
      mount /dev/disk/by-label/nixos /btrfs_tmp
      if [[ -e /btrfs_tmp/root ]]; then
	  mkdir -p /btrfs_tmp/old_roots
	  timestamp=$(date --date="@$(stat -c %Y /btrfs_tmp/root)" "+%Y-%m-%-d_%H:%M:%S")
	  mv /btrfs_tmp/root "/btrfs_tmp/old_roots/$timestamp"
      fi

      delete_subvolume_recursively() {
	  IFS=$'\n'
	  for i in $(btrfs subvolume list -o "$1" | cut -f 9- -d ' '); do
	      delete_subvolume_recursively "/btrfs_tmp/$i"
	  done
	  btrfs subvolume delete "$1"
      }

      # Delete root older than 30 days
      for i in $(find /btrfs_tmp/old_roots/ -maxdepth 1 -mtime +30); do
	  delete_subvolume_recursively "$i"
      done

      btrfs subvolume create /btrfs_tmp/root
      umount /btrfs_tmp
    '';
  };


  fileSystems."/nix" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [
      "subvol=nix"
    ];
    neededForBoot = true;
  };

  fileSystems."/btrfs-root" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/boot";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077" "defaults"];
  };

  fileSystems."/persistent" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "btrfs";
    options = [ "subvol=persistent" ];
    neededForBoot = true;
  };

  swapDevices = [
    {device = "/dev/disk/by-label/swap";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  networking.hostName = "Kakariko"; # Define your hostname.
  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/639bca5e-580f-4bbd-9b12-1db78906d356";
      preLVM = true;
    };
  };
  services.xmr-stak.openclSupport = true;
  hardware.opengl.extraPackages = with pkgs; [
    mesa
    amdvlk
    qt6.full
    log4cxx
  ];
}
