# This is a basic workflow to help you get started with Actions

name: Deploy Servers

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: deploy
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    # The type of runner that the job will run on
    runs-on: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Deploy Servers
        env: 
          SSH_KNOWN_HOSTS: ${{secrets.SSH_KNOWN_HOSTS}}
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
        run: |
          echo "$SSH_PRIVATE_KEY" > id_ed25519 
          chmod 600 id_ed25519
          echo "$SSH_KNOWN_HOSTS" > known_hosts
          ssh -i id_ed25519 -o UserKnownHostsFile=known_hosts root@nix-samba-dc.ad.astahhu.de echo a
          deploy --skip-checks --ssh-user root --ssh-opts "-i id_ed25519 -o UserKnownHostsFile=known_hosts -o HostKeyAlgorithms=ssh-ed25519"
